"""One figure with its full traceability chain back to the bytes (fusion s1 'Traceable',
extraction s1 'Traceable to bytes', s11 observation reading).

Figure: the count of JETP-aligned projects MOIT states in newsletter issue 13.
Each link is re-verified from the stored bytes, not copied: the snapshot is re-hashed,
the text layer is regenerated by the named adapter, and the anchor, label and value are
found again.
"""
import csv
import hashlib
import json
import re
import subprocess

DOC = 'vnm-moit-newsletter-13-2026-03'
SHA = 'fa7d149b3d8165b85b7090584a3df3d35fbd6b097bb8a08844df330a3410fc39'
ORD = 9
D = 'data/jetp/'


def ws(s):
    return re.sub(r'\s+', ' ', s).strip()


loc = json.load(open(f'spike/out/{DOC}/located.json'))
st = next(s for s in loc['kept'] if s['ordinal'] == ORD)
chk = next(c for c in json.load(open(f'spike/out/{DOC}/checks.json'))['checks'] if c['ordinal'] == ORD)
prop = json.load(open(f'spike/out/{DOC}/proposals.json'))['_method']
snap = next(r for r in csv.DictReader(open(D + 'snapshots.csv')) if r['sha256'] == SHA)
rets = [r for r in csv.DictReader(open(D + 'retrievals.csv')) if r['sha256'] == SHA]
doc = next(r for r in csv.DictReader(open(D + 'documents.csv')) if r['document_id'] == DOC)
pubs = [r for r in csv.DictReader(open(D + 'document-publishers.csv')) if r['document_id'] == DOC]

# re-verify from the bytes
b = open(D + 'documents/' + snap['storage_path'], 'rb').read()
hash_ok = hashlib.sha256(b).hexdigest() == SHA
page_txt = subprocess.run(['pdftotext', '-f', str(st['page']), '-l', str(st['page']),
                           D + 'documents/' + snap['storage_path'], '-'], capture_output=True, text=True).stdout
joined = ws(page_txt)
anchor_ok = joined.count(st['locator']['text_anchor']) == 1
label_ok = ws(st['label']) in joined
m = re.search(r'danh mục (\d+) dự án phù hợp JETP', joined)
value_ok = bool(m) and m.group(1) == '44'

chain = {
    'figure': {'value': 44, 'unit': 'dự án (projects), a count the publisher stated (fusion s7: unit named)',
               'reads': 'MOIT newsletter issue 13 states that the parties have identified a list of 44 JETP-aligned projects with a capital need of over USD 11 billion',
               'note': 'a publisher-stated count, not a count of identities; no project identity is minted from it (fusion s7, s9 row 8)'},
    'observation_as_it_would_be_read_at_M3b': {
        'subject_kind': 'line', 'subject_id': f'{DOC}-text-{ORD}', 'axis': 'counting', 'measure': 'count',
        'value': '44', 'value_low': '44', 'value_high': '44', 'unit': 'dự án',
        'timings': [{'date_role': 'event', 'date': '2026-03-27', 'date_precision': 'day',
                     'problem': "the article prints 'Ngày 27/3' without a year; the year is on the masthead "
                                "'Số 13 – Tháng 03/2026', which the reader declared out of scope as page furniture, "
                                "so no statement of this snapshot carries it (extraction s11 requires the timing to "
                                "name the statement it was read from)"}],
        'method': 'not run: observation reading is M3b (extraction s11)'},
    'statement': {'line_id_as_minted': f'{DOC}-text-{ORD}', 'country': doc['country'], 'sha256': SHA,
                  'locator': st['locator'], 'ordinal': ORD, 'label': st['label'],
                  'classification': st['classification'], 'fields': st.get('fields'),
                  'group_anchor': st.get('group_anchor'),
                  'method': prop['method'], 'method_version': prop['version'], 'reader': prop['reader'],
                  'checker': json.load(open(f'spike/out/{DOC}/checks.json'))['_method']['checker'],
                  'checker_stance': chk, 'author_decision': 'pending: shown to the author as a disagreement (partly right, likely, medium)'},
    'text_layer': {'adapter': st['locator']['adapter'], 'regenerated_now': True,
                   'anchor_resolves_once': anchor_ok, 'label_found': label_ok, 'value_44_found_in_label': value_ok},
    'snapshot': {**snap, 'bytes_rehashed_match': hash_ok, 'size_on_disk': len(b)},
    'retrievals': rets,
    'document': doc,
    'document_publishers': pubs,
    'knowledge_time': {'recorded_date_rule': 'extraction s3: when the ledger admitted the statement; the date the ledger first held the bytes is the earliest retrieval yielding the snapshot',
                       'first_held': min(r['retrieved_at'] for r in rets) if rets else None},
}
chain['all_links_verified'] = hash_ok and anchor_ok and label_ok and value_ok and bool(rets)
json.dump(chain, open('spike/out/figure_trace.json', 'w'), ensure_ascii=False, indent=1)
print(json.dumps({k: chain[k] for k in ('figure', 'text_layer', 'all_links_verified')}, ensure_ascii=False, indent=1))
print('retrievals', [(r['retrieval_id'], r['retrieved_at'], r['final_url']) for r in rets])
print('publishers', pubs)
