project:
  render:
    - "!content/corpus-report.qmd"
    - "!content/technical-report.qmd"
    - "!content/breakpoint-detect-method-zoo.qmd"
    - "!content/data-paper.qmd"
    - "!content/multilayer-detection.qmd"
